device: cuda

data:
  batch_size: 32
  sequence_length: 50
  num_workers: 2

observation:
  observation_dim: 64 # 40 if using states else 32
  embedding_dim: 128
  use_states: True
  fusion_type: "cross_attention"

action:
  num_bins: 32
  action_dim: 2

bet_model:
  num_transformer_layers: 8
  num_attention_heads: 4

training:
  epochs: 500
  residual_loss_scale: 5
  learning_rate: 0.0001
  weight_decay: 0.02
  betas: [0.9, 0.999]
  gamma: 1
  eval_interval: 1 # is also the save interval
  checkpoint_path: "./checkpoint"

evaluation:
  save_video: True
  video_dir: "./eval_videos"
  num_rollout: 100
  max_episode_steps: 300
  checkpoint_path: "/home/zogmohan/GIT_1/BeT-PushT/checkpoint/checkpoint_epoch0.pth"