device: cuda

data:
  batch_size: 256
  sequence_length: 5
  num_workers: 8

observation:
  observation_dim: 64 # 40 if using states else 32
  embedding_dim: 128
  use_states: True
  fusion_type: "cross_attention"
  encoder_type: "cnn" # "resnet" or "cnn"

action:
  num_bins: 24
  action_dim: 2

bet_model:
  num_transformer_layers: 4
  num_attention_heads: 4
  dropout: 0.1

training:
  epochs: 500
  residual_loss_scale: 1
  learning_rate: 0.0001
  weight_decay: 0.01
  betas: [0.9, 0.95]
  gamma: 1
  eval_interval: 1
  save_interval: 10
  checkpoint_path: "./checkpoint_4_4_8_w5_cross"

evaluation:
  save_video: True
  video_dir: "./eval_videos_4_4_8_w5_cross"
  num_rollout: 100
  max_episode_steps: 300
  checkpoint_path: "./checkpoint_4_4_8_w5_cross/checkpoint_epoch15.pth"
