device: cpu

data:
  zarr_path: "./pusht/pusht_cchi_v7_replay.zarr"
  batch_size: 2
  sequence_length: 5
  num_workers: 8

observation:
  state_dim: 5
  observation_dim: 32   # output of StateObservation -> input to BeT
  embedding_dim: 64     # BeT internal embedding
  dropout: 0.1

action:
  num_bins: 24
  action_dim: 2

bet_model:
  num_transformer_layers: 1
  num_attention_heads: 1
  dropout: 0.1

training:
  epochs: 500
  residual_loss_scale: 1
  learning_rate: 0.0001
  weight_decay: 0.01
  betas: [0.9, 0.95]
  gamma: 1
  eval_interval: 1
  save_interval: 10
  checkpoint_path: "./checkpoint"

evaluation:
  save_video: true
  video_dir: "./eval_videos_pusht"
  num_rollout: 100
  max_episode_steps: 500
  checkpoint_path: "./checkpoint/checkpoint_epoch10.pth"
